spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pinyougoudb?useSSL=false
    username: gxl
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  aop:
    proxy-target-class: false
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
server:
  port: 8081